# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e2b0f23966e3ac71ff35c71ea827483cc3f1d2ab025bf5310f8b0126f640744e836616073c576825589445d715d9aa029430b4266e7cacd7e7b8d1082225531

test:
  secret_key_base: dcbf08379b8fa11de4fea074672ee1058d2c6472c3477d94ea0914e30ba56950a3cb02bf69062c46d9414852f78c0ea890ce2b468d271340017aa9f948f7e6e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
